version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    command: /entrypoint.sh
    volumes:
      - ./:/var/www/html
      - ./.docker/supervisor/supervisord.conf:/etc/supervisord.conf
      - ./.docker/php/entrypoint.sh:/entrypoint.sh
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8066:80"
      - "4466:443"
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./.docker/nginx/ssl/:/etc/nginx/ssl/
    networks:
      - laravel

  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "${DB_HOST_PORT}:${DB_PORT}"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./.docker/mysql/dbdata:/var/lib/mysql/
      - ./.docker/mysql/dump:/docker-entrypoint-initdb.d
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
volumes:
  mysqldata:
    driver: local
